[pytest]
; 默认命令行参数
addopts = -v -s --html=report/report.html --self-contained-html --maxfail=2

; 测试路径
testpaths = tests

; 文件命名规则
python_files = test_*.py
python_classes = Test*
python_functions = test_*

; 注册标记（必须！）
markers =
    smoke: 冒烟测试，用于快速验证核心功能
    regression: 回归测试，全量验证
    xfail: 预期失败的测试